/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#121315',
        'surface-dim': '#0a0b0d',
        'surface-bright': '#38393b',
        'surface-container-lowest': '#0d0e10',
        'surface-container-low': '#1b1c1e',
        'surface-container': '#1f2022',
        'surface-container-high': '#292a2c',
        'surface-container-highest': '#343537',
        'surface-variant': '#343537',
        'on-surface': '#e3e2e5',
        'on-surface-variant': '#c2c6d6',
        'background': '#121315',
        'on-background': '#e3e2e5',
        'primary': '#adc6ff',
        'primary-container': '#4d8eff',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary': '#002e6a',
        'on-primary-container': '#00285d',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary': '#b1c6f9',
        'secondary-container': '#304671',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#b1c6f9',
        'on-secondary': '#182f59',
        'on-secondary-container': '#9fb5e7',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#304671',
        'tertiary': '#ffb786',
        'tertiary-container': '#df7412',
        'on-tertiary': '#502400',
        'on-tertiary-container': '#461f00',
        'outline': '#8c909f',
        'outline-variant': '#424754',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error': '#690005',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e3e2e5',
        'inverse-on-surface': '#303033',
        'inverse-primary': '#005ac2',
        'surface-tint': '#adc6ff',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'monospace'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
};
